pipeline {
    
    agent any

    tools { 
        maven 'maven3' 
    }

    options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '15', 
                    numToKeepStr: '10'
            )
    }

    environment {
        APP_NAME = "DCUBE_APP"
        APP_ENV  = "DEV"
    }

    stages {
        
        stage('Cleanup Workspace') {
            steps {
                dir("C:/Users/elias/Documents/dev/jenkins") {
                    cleanWs()
                    bat """
                    echo "Cleaned Up Workspace for ${APP_NAME}"
                    """
                }
            }
        }

        stage('Code Checkout') {
            steps {
                dir("C:/Users/elias/Documents/dev/jenkins") {
                    
                    git branch: 'master', url: 'https://github.com/eliasmichalczuk/simple-java-maven-app'
                }
            }
        }

        stage('Code Build') {
            steps {
                dir("C:/Users/elias/Documents/dev/jenkins") {
                    
                    bat 'mvn install -Dmaven.test.skip=true'
                }
            }
        }
        
        stage('Priting All Global Variables') {
            steps {
                bat """
                echo %env%
                """
            }
        }


    }   
}
